<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Report</title>

    <style>

        @page {
            margin: 0;
            size: A4;
        }

    </style>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<div class="container-fluid">

    <h1 class="text-secondary text-center text-capitalize">Expense Report for {{$type}}</h1>
    <p class="small text-center text-secondary mb-0">Generated on: {{$generated->format('Y-m-d')}}</p>
    <p class="small text-center text-secondary">Generated by: {{Auth::user()->name}}</p>
    <p class="small text-center text-secondary">Coverage: {{$date}}</p>

    <div class="table-responsive">
         <table class="table table-bordered">
            <thead>
            <tr>

                @if($type !== 'organization')
                      <th>Recipient</th>
                @endif

                <th>Amount</th>
                <th>Purpose</th>
                <th>Date</th>
            </tr>
            </thead>
            <tbody>
                @forelse ($expenses as $expenses)
                    <tr>

                        @if($type !== 'organization')
                            <td>{{$expenses->recipient->name}}</td>
                        @endif

                        <td>{{$expenses->amount}}</td>
                        <td>{{$expenses->purpose}}</td>
                        <td>{{$expenses->created_at}}</td>
                    </tr>
                @empty
                    <tr>
                        <td class="text-secondary mh-100 text-center" colspan="4">EMPTY</td>
                    </tr>
                @endforelse
            </tbody>
         </table>
    </div>

</div>
</body>
</html>